version: '2'
services:
  cl2-web:
    image: node:latest
    command: npm run deploy
    working_dir: /app
    expose:
     - 8090
    volumes:
     - .:/app
    depends_on:
     - cl2-mongo

  cl2-mongo:
    image: mongo:latest
    #volumes:
    # - ./.data/mongo:/data/db

  cl2-testing:
    image: node:latest
    command: npm run testing
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - cl2-web
    environment:
      TEST_URI: ws://cl2-web:8090/